apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-go-dinsdizw
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/tsscui/backend-tests-go-dinsdizw:6242f531406f1f45af28e01c54e90c4921bb8fed@sha256:79c361ef1e36e21c43137097e8be3b45994f552ad81b51d48d1f157d41c7a3af
        name: container-image  
