apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-dinsdizw
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/backend-tests-go-dinsdizw:b40db9b50729d4a0ef59429f8a72fc0c5a9dc771@sha256:88ec0bb12dfd1913de27bc44226d3f91465d17a40e00c4b64baf96b4092e9995
          name: container-image
